import type { AdminDictionary } from "./index";

export const adminEn: AdminDictionary = {
  common: {
    logout: "Log out",
    save: "Save",
    back: "Back",
    actions: "Actions",
    edit: "Edit",
    view: "View",
    status: "Status",
    language: "Language",
    set: "Set",
  },
  nav: {
    dashboard: "Dashboard",
    leads: "Leads",
    bookings: "Bookings",
    content: "Content",
    services: "Services",
    industries: "Industries",
    users: "Users",
    auditLogs: "Audit logs",
    settings: "Settings",
  },
  login: {
    subtitle: "Sign in to continue",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signingIn: "Signing in…",
    forgot: "Forgot password?",
    noticeInvited: "Account created. You can now sign in.",
    noticeReset: "Password updated. Sign in with your new password.",
  },
  forgot: {
    title: "Reset password",
    subtitle: "Enter your email to receive a reset link",
    email: "Email",
    send: "Send reset link",
    sending: "Sending…",
    sent: "If that email exists, a password reset link has been sent.",
    back: "Back to sign in",
  },
  reset: {
    title: "Set a new password",
    newPassword: "New password",
    hint: "at least 10 characters",
    save: "Reset password",
    saving: "Saving…",
    missing: "This reset link is missing or invalid.",
    back: "Back to sign in",
  },
  invite: {
    title: "Accept invite",
    subtitle: "Set your password to activate your account",
    name: "Your name",
    createPassword: "Create password",
    hint: "at least 10 characters",
    create: "Create account",
    creating: "Creating…",
    missing: "This invite link is missing or invalid.",
    back: "Back to sign in",
  },
  forbidden: {
    title: "Access denied",
    body: "You don't have permission to view this page. Contact a Super Admin if you think this is a mistake.",
    back: "Back to dashboard",
  },
  errors: {
    notAvailable: "Authentication is not available yet.",
    invalidCreds: "Invalid email or password.",
    notActive: "Your account is not active. Contact an administrator.",
    passwordShort: "Password must be at least 10 characters.",
    inviteInvalid: "This invite is invalid or has expired.",
    resetInvalid: "This reset link is invalid or has expired.",
    superAdminInvite: "Super Admin cannot be invited from the panel.",
    invalidEmail: "Enter a valid email.",
  },
  dashboard: {
    welcome: "Welcome",
    overview: "Overview of leads, bookings, and recent activity.",
    newToday: "New leads today",
    qualified: "Qualified",
    won: "Won",
    pendingBookings: "Pending bookings",
    failedNotifications: "Failed notifications",
    failedHint: "need retry",
    recentActivity: "Recent activity",
    noActivity: "No activity yet.",
  },
  leads: {
    title: "Leads",
    description: "Consultation requests from the landing page.",
    exportCsv: "Export CSV",
    all: "All",
    colName: "Name",
    colCompany: "Company",
    colContact: "Contact",
    colSolution: "Solution",
    colCreated: "Created",
    empty: "No leads match this view yet.",
  },
  leadDetail: {
    submitted: "Submitted",
    details: "Details",
    company: "Company",
    solution: "Interested solution",
    phone: "Phone",
    email: "Email",
    source: "Source",
    sourcePage: "Source page",
    message: "Message",
    notes: "Notes",
    addNotePlaceholder: "Add an internal note…",
    addNote: "Add note",
    noNotes: "No notes yet.",
    status: "Status",
    updateStatus: "Update status",
    assignment: "Assignment",
    assignedTo: "Assigned to",
    unassigned: "Unassigned",
    assign: "Assign",
    delivery: "Delivery",
    notification: "Notification",
    consent: "Consent",
    yes: "Yes",
    no: "No",
    utmSource: "UTM source",
    archive: "Archive",
  },
  users: {
    title: "Users",
    description: "Admin team members (invite-only).",
    inviteTitle: "Invite a team member",
    emailPlaceholder: "email@company.com",
    sendInvite: "Send invite",
    inviting: "Inviting…",
    inviteCreated: "Invite created.",
    role: "Role",
    deactivate: "Deactivate",
    reactivate: "Reactivate",
    colName: "Name",
    colEmail: "Email",
    colRoles: "Roles",
    colLastLogin: "Last login",
    empty: "No users yet.",
  },
  bookings: {
    title: "Bookings",
    description: "Consultation booking requests.",
    colName: "Name",
    colContact: "Contact",
    colPreferred: "Preferred",
    archive: "Archive",
    empty: "No bookings yet.",
  },
  services: {
    title: "Services",
    description: "Service blocks. Published items replace the default copy on the landing page.",
    new: "New service",
    colTitle: "Title",
    colLang: "Lang",
    colOrder: "Order",
    publish: "Publish",
    archive: "Archive",
    toDraft: "To draft",
    empty: "No services yet. The landing page uses the default copy until you publish some.",
    newTitle: "New service",
    newDesc: "Create a service block (saved as draft).",
  },
  industries: {
    title: "Industries",
    description: "Industry groups. Published items replace the default copy on the landing page.",
    new: "New industry",
    colTitle: "Title",
    colLang: "Lang",
    colOrder: "Order",
    publish: "Publish",
    archive: "Archive",
    toDraft: "To draft",
    empty: "No industries yet. The landing page uses the default copy until you publish some.",
    newTitle: "New industry",
    newDesc: "Create an industry group (saved as draft).",
  },
  form: {
    language: "Language",
    order: "Order",
    title: "Title",
    slug: "Slug",
    slugHint: "stable, e.g. crm-systems",
    category: "Category",
    categoryHint: "e.g. New customer acquisition",
    group: "Group",
    groupHint: "e.g. Sales and customer businesses",
    iconKey: "Icon key",
    iconHint: "optional",
    goal: "Goal (short description)",
    included: "Included services",
    includedHint: "one per line",
    businessValue: "Business value",
    fullDescription: "Full description",
    examples: "Example sectors (description)",
    recommendedSolutions: "Recommended solutions",
    seoTitle: "SEO title",
    seoDescription: "SEO description",
    save: "Save",
  },
  content: {
    title: "Content",
    description: "Landing page section copy — editable per language.",
    note: "Changes appear on the landing page only after you publish. Until then the default copy is shown.",
    edit: "Edit",
    saved: "Saved",
    publish: "Publish",
    archive: "Archive",
    toDraft: "To draft",
    language: "Language",
    save: "Save",
    sections: {
      hero: "Hero",
      pain: "Pain section",
      solution: "Solutions",
      success: "Success key",
      results: "Results",
      ai: "AI section",
      process: "Process",
      trust: "Trust",
      cta: "CTA / Form",
    },
  },
  settings: {
    title: "Settings",
    description: "Integrations and contact details.",
    integrationStatus: "Integration status",
    configured: "Configured",
    notConfigured: "Not configured",
    database: "Database (PostgreSQL)",
    emailSmtp: "Email (SMTP)",
    telegram: "Telegram",
    analytics: "Analytics (GA4)",
    booking: "Booking (Calendly)",
    secretsNote:
      "Secrets are configured via environment variables and are never shown here. Only a Super Admin can manage integration secrets.",
    contactTitle: "Contact (placeholders)",
    contactNote: "Edit in src/config/contact.ts until the editable settings form is wired.",
    testTitle: "Test notification",
    testButton: "Send test notification",
    testRunning: "Sending…",
    resultSent: "Sent",
    resultFailed: "Failed",
    resultSkipped: "Skipped",
  },
  audit: {
    title: "Audit logs",
    description: "Immutable record of important actions.",
    colAction: "Action",
    colEntity: "Entity",
    colActorRole: "Actor role",
    colIp: "IP",
    colWhen: "When",
    empty: "No audit entries yet.",
  },
  leadStatus: {
    NEW: "New",
    CONTACTED: "Contacted",
    QUALIFIED: "Qualified",
    PROPOSAL_SENT: "Proposal sent",
    WON: "Won",
    LOST: "Lost",
    REJECTED: "Rejected",
    SPAM: "Spam",
    DUPLICATE: "Duplicate",
    ARCHIVED: "Archived",
  },
  bookingStatus: {
    NEW: "New",
    CONFIRMED: "Confirmed",
    RESCHEDULED: "Rescheduled",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    NO_SHOW: "No show",
    ARCHIVED: "Archived",
  },
  contentStatus: {
    DRAFT: "Draft",
    PENDING_REVIEW: "Pending review",
    APPROVED: "Approved",
    PUBLISHED: "Published",
    REJECTED: "Rejected",
    ARCHIVED: "Archived",
  },
  userStatus: {
    PENDING_APPROVAL: "Pending approval",
    ACTIVE: "Active",
    SUSPENDED: "Suspended",
    REJECTED: "Rejected",
    DEACTIVATED: "Deactivated",
  },
  roles: {
    super_admin: "Super Admin",
    admin: "Admin",
    editor: "Editor",
    moderator: "Moderator",
    sales_lead_manager: "Sales / Lead Manager",
    viewer: "Viewer",
  },
};
