// Admin panel dictionary (Armenian, canonical). The type is derived from this.
export const adminHy = {
  common: {
    logout: "Դուրս գալ",
    save: "Պահպանել",
    back: "Հետ",
    actions: "Գործողություններ",
    edit: "Խմբագրել",
    view: "Դիտել",
    status: "Կարգավիճակ",
    language: "Լեզու",
    set: "Կիրառել",
  },
  nav: {
    dashboard: "Վահանակ",
    leads: "Հայտեր",
    bookings: "Ամրագրումներ",
    content: "Բովանդակություն",
    services: "Ծառայություններ",
    industries: "Ոլորտներ",
    users: "Օգտատերեր",
    auditLogs: "Աուդիտ",
    settings: "Կարգավորումներ",
  },
  login: {
    subtitle: "Մուտք գործեք շարունակելու համար",
    email: "Email",
    password: "Գաղտնաբառ",
    signIn: "Մուտք",
    signingIn: "Մուտք…",
    forgot: "Մոռացե՞լ եք գաղտնաբառը",
    noticeInvited: "Հաշիվը ստեղծված է։ Հիմա կարող եք մուտք գործել։",
    noticeReset: "Գաղտնաբառը թարմացված է։ Մուտք գործեք նոր գաղտնաբառով։",
  },
  forgot: {
    title: "Գաղտնաբառի վերականգնում",
    subtitle: "Մուտքագրեք email-ը՝ վերականգնման հղում ստանալու համար",
    email: "Email",
    send: "Ուղարկել հղումը",
    sending: "Ուղարկվում է…",
    sent: "Եթե այդ email-ը գոյություն ունի, վերականգնման հղումն ուղարկվել է։",
    back: "Վերադառնալ մուտքին",
  },
  reset: {
    title: "Նոր գաղտնաբառ",
    newPassword: "Նոր գաղտնաբառ",
    hint: "նվազագույնը 10 նիշ",
    save: "Վերականգնել գաղտնաբառը",
    saving: "Պահպանվում է…",
    missing: "Այս հղումը բացակայում է կամ սխալ է։",
    back: "Վերադառնալ մուտքին",
  },
  invite: {
    title: "Հրավերի ընդունում",
    subtitle: "Սահմանեք գաղտնաբառ՝ հաշիվն ակտիվացնելու համար",
    name: "Ձեր անունը",
    createPassword: "Ստեղծել գաղտնաբառ",
    hint: "նվազագույնը 10 նիշ",
    create: "Ստեղծել հաշիվ",
    creating: "Ստեղծվում է…",
    missing: "Այս հրավերի հղումը բացակայում է կամ սխալ է։",
    back: "Վերադառնալ մուտքին",
  },
  forbidden: {
    title: "Մուտքն արգելված է",
    body: "Դուք չունեք այս էջը դիտելու թույլտվություն։ Եթե սա սխալ է, դիմեք Super Admin-ին։",
    back: "Վերադառնալ վահանակ",
  },
  errors: {
    notAvailable: "Նույնականացումը դեռ հասանելի չէ։",
    invalidCreds: "Սխալ email կամ գաղտնաբառ։",
    notActive: "Ձեր հաշիվն ակտիվ չէ։ Դիմեք ադմինիստրատորին։",
    passwordShort: "Գաղտնաբառը պետք է լինի առնվազն 10 նիշ։",
    inviteInvalid: "Այս հրավերը անվավեր է կամ ժամկետանց։",
    resetInvalid: "Այս վերականգնման հղումն անվավեր է կամ ժամկետանց։",
    superAdminInvite: "Super Admin-ը չի կարող հրավիրվել վահանակից։",
    invalidEmail: "Մուտքագրեք վավեր email։",
    roleNotAllowed: "Դուք չունեք այս դերը նշանակելու թույլտվություն։",
    tooManyAttempts: "Չափից շատ փորձեր։ Փորձեք մի փոքր ուշ։",
  },
  dashboard: {
    welcome: "Բարի գալուստ",
    overview: "Հայտերի, ամրագրումների և գործունեության ընդհանուր պատկեր։",
    newToday: "Նոր հայտեր այսօր",
    qualified: "Որակավորված",
    won: "Շահված",
    pendingBookings: "Սպասող ամրագրումներ",
    failedNotifications: "Ձախողված ծանուցումներ",
    failedHint: "պահանջում են կրկնում",
    recentActivity: "Վերջին գործունեություն",
    noActivity: "Դեռ գործունեություն չկա։",
  },
  leads: {
    title: "Հայտեր",
    description: "Խորհրդատվության հայտեր landing էջից։",
    exportCsv: "Արտահանել CSV",
    all: "Բոլորը",
    colName: "Անուն",
    colCompany: "Ընկերություն",
    colContact: "Կոնտակտ",
    colSolution: "Լուծում",
    colCreated: "Ստեղծվել է",
    empty: "Այս տեսքում դեռ հայտ չկա։",
  },
  leadDetail: {
    submitted: "Ուղարկվել է",
    details: "Մանրամասներ",
    company: "Ընկերություն",
    solution: "Հետաքրքրող լուծում",
    phone: "Հեռախոս",
    email: "Email",
    source: "Աղբյուր",
    sourcePage: "Աղբյուր էջ",
    message: "Հաղորդագրություն",
    notes: "Նշումներ",
    addNotePlaceholder: "Ավելացրեք ներքին նշում…",
    addNote: "Ավելացնել նշում",
    noNotes: "Դեռ նշում չկա։",
    status: "Կարգավիճակ",
    updateStatus: "Թարմացնել կարգավիճակը",
    assignment: "Նշանակում",
    assignedTo: "Նշանակված է՝",
    unassigned: "Չնշանակված",
    assign: "Նշանակել",
    delivery: "Առաքում",
    notification: "Ծանուցում",
    resendNotification: "Կրկին ուղարկել ծանուցումը",
    consent: "Համաձայնություն",
    yes: "Այո",
    no: "Ոչ",
    utmSource: "UTM source",
    archive: "Արխիվացնել",
  },
  users: {
    title: "Օգտատերեր",
    description: "Ադմին թիմի անդամներ (միայն հրավերով)։",
    inviteTitle: "Հրավիրել թիմի անդամ",
    emailPlaceholder: "email@company.com",
    sendInvite: "Ուղարկել հրավեր",
    inviting: "Հրավիրվում է…",
    inviteCreated: "Հրավերը ստեղծված է։",
    role: "Դեր",
    deactivate: "Ապաակտիվացնել",
    reactivate: "Վերաակտիվացնել",
    colName: "Անուն",
    colEmail: "Email",
    colRoles: "Դերեր",
    colLastLogin: "Վերջին մուտք",
    empty: "Դեռ օգտատեր չկա։",
  },
  bookings: {
    title: "Ամրագրումներ",
    description: "Խորհրդատվության ամրագրման հայտեր։",
    colName: "Անուն",
    colContact: "Կոնտակտ",
    colPreferred: "Նախընտրելի",
    archive: "Արխիվացնել",
    empty: "Դեռ ամրագրում չկա։",
  },
  services: {
    title: "Ծառայություններ",
    description:
      "Ծառայության բլոկներ։ Published-ները փոխարինում են landing-ի լռելյայն տեքստը։",
    new: "Նոր ծառայություն",
    colTitle: "Վերնագիր",
    colLang: "Լեզու",
    colOrder: "Հերթ",
    publish: "Հրապարակել",
    archive: "Արխիվ",
    toDraft: "Սևագիր",
    empty: "Դեռ ծառայություն չկա։ Մինչ publish անելը landing-ը օգտագործում է լռելյայն տեքստը։",
    newTitle: "Նոր ծառայություն",
    newDesc: "Ստեղծեք ծառայության բլոկ (պահվում է որպես սևագիր)։",
  },
  industries: {
    title: "Ոլորտներ",
    description:
      "Ոլորտների խմբեր։ Published-ները փոխարինում են landing-ի լռելյայն տեքստը։",
    new: "Նոր ոլորտ",
    colTitle: "Վերնագիր",
    colLang: "Լեզու",
    colOrder: "Հերթ",
    publish: "Հրապարակել",
    archive: "Արխիվ",
    toDraft: "Սևագիր",
    empty: "Դեռ ոլորտ չկա։ Մինչ publish անելը landing-ը օգտագործում է լռելյայն տեքստը։",
    newTitle: "Նոր ոլորտ",
    newDesc: "Ստեղծեք ոլորտի խումբ (պահվում է որպես սևագիր)։",
  },
  form: {
    language: "Լեզու",
    order: "Հերթ",
    title: "Վերնագիր",
    slug: "Slug",
    slugHint: "կայուն, օր․ crm-systems",
    category: "Կատեգորիա",
    categoryHint: "օր․ Նոր հաճախորդների ներգրավում",
    group: "Խումբ",
    groupHint: "օր․ Վաճառքի բիզնեսներ",
    iconKey: "Icon key",
    iconHint: "ոչ պարտադիր",
    goal: "Նպատակ (կարճ նկարագրություն)",
    included: "Ներառված ծառայություններ",
    includedHint: "մեկը մի տողում",
    businessValue: "Բիզնես արժեք",
    fullDescription: "Լրիվ նկարագրություն",
    examples: "Օրինակ ոլորտներ (նկարագրություն)",
    recommendedSolutions: "Առաջարկվող լուծումներ",
    seoTitle: "SEO վերնագիր",
    seoDescription: "SEO նկարագրություն",
    save: "Պահպանել",
  },
  content: {
    title: "Բովանդակություն",
    description: "Landing էջի բաժինների տեքստը՝ խմբագրելի ըստ լեզվի։",
    note: "Փոփոխությունները landing-ում երևում են միայն publish անելուց հետո։ Մինչ publish-ը՝ ցույց է տրվում լռելյայն տեքստը։",
    edit: "Խմբագրել",
    saved: "Պահպանված է",
    publish: "Հրապարակել",
    archive: "Արխիվ",
    toDraft: "Սևագիր",
    language: "Լեզու",
    save: "Պահպանել",
    sections: {
      hero: "Գլխավոր (Hero)",
      pain: "Խնդիրներ",
      solution: "Լուծումներ",
      success: "Հաջողության բանալի",
      results: "Արդյունքներ",
      ai: "Արհեստական բանականություն",
      process: "Մոտեցում",
      trust: "Վստահություն",
      cta: "Կոչ / Հայտ",
    },
  },
  settings: {
    title: "Կարգավորումներ",
    description: "Ինտեգրացիաներ և կոնտակտներ։",
    integrationStatus: "Ինտեգրացիաների վիճակ",
    configured: "Կարգավորված",
    notConfigured: "Չկարգավորված",
    database: "Տվյալների բազա (PostgreSQL)",
    emailSmtp: "Email (SMTP)",
    telegram: "Telegram",
    analytics: "Analytics (GA4)",
    booking: "Ամրագրում (Calendly)",
    secretsNote:
      "Secret-ները կարգավորվում են environment փոփոխականներով և երբեք այստեղ չեն ցուցադրվում։ Միայն Super Admin-ը կարող է կառավարել secret-ները։",
    contactTitle: "Կոնտակտ (placeholder)",
    contactNote: "Խմբագրեք src/config/contact.ts-ում մինչ կարգավորումների ձևի միացումը։",
    testTitle: "Թեստ ծանուցում",
    testButton: "Ուղարկել թեստ ծանուցում",
    testRunning: "Ուղարկվում է…",
    resultSent: "Ուղարկված",
    resultFailed: "Ձախողված",
    resultSkipped: "Չկարգավորված",
  },
  audit: {
    title: "Աուդիտ",
    description: "Կարևոր գործողությունների անփոփոխ գրառում։",
    colAction: "Գործողություն",
    colEntity: "Օբյեկտ",
    colActorRole: "Դեր",
    colIp: "IP",
    colWhen: "Երբ",
    empty: "Դեռ աուդիտ գրառում չկա։",
  },
  leadStatus: {
    NEW: "Նոր",
    CONTACTED: "Կապ հաստատված",
    QUALIFIED: "Որակավորված",
    PROPOSAL_SENT: "Առաջարկ ուղարկված",
    WON: "Շահված",
    LOST: "Կորցրած",
    REJECTED: "Մերժված",
    SPAM: "Spam",
    DUPLICATE: "Կրկնակ",
    ARCHIVED: "Արխիվ",
  },
  bookingStatus: {
    NEW: "Նոր",
    CONFIRMED: "Հաստատված",
    RESCHEDULED: "Վերանշանակված",
    COMPLETED: "Ավարտված",
    CANCELLED: "Չեղարկված",
    NO_SHOW: "Չներկայացած",
    ARCHIVED: "Արխիվ",
  },
  contentStatus: {
    DRAFT: "Սևագիր",
    PENDING_REVIEW: "Սպասում է ստուգման",
    APPROVED: "Հաստատված",
    PUBLISHED: "Հրապարակված",
    REJECTED: "Մերժված",
    ARCHIVED: "Արխիվ",
  },
  userStatus: {
    PENDING_APPROVAL: "Սպասում է հաստատման",
    ACTIVE: "Ակտիվ",
    SUSPENDED: "Կասեցված",
    REJECTED: "Մերժված",
    DEACTIVATED: "Ապաակտիվացված",
  },
  roles: {
    super_admin: "Super Admin",
    admin: "Ադմին",
    editor: "Խմբագիր",
    moderator: "Մոդերատոր",
    sales_lead_manager: "Վաճառքի մենեջեր",
    viewer: "Դիտող",
  },
};
